apiVersion: 1
datasources:
  - name: Nodera telemetry
    type: grafana-clickhouse-datasource
    uid: nodera-clickhouse
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: nodera
      username: $CLICKHOUSE_USER
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
