package dev.nodera.protocol.wire;

import dev.nodera.protocol.NoderaMessage;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * The current build against a <b>previous release's</b> wire corpus (network task 14, phase 7).
 *
 * <p>The in-repo suites all measure this build against itself: the fixtures are regenerated by the
 * same encoder that is being checked, so they can only ever prove internal consistency. This test
 * takes bytes produced by a <i>different revision</i> of the project — handed to it as a directory
 * through {@code -Dnodera.wire.previousCorpus} — and asserts what the current build does with them.
 *
 * <p>What it asserts depends on the epoch those bytes carry, and it reads that out of the bytes
 * rather than being told:
 *
 * <ul>
 *   <li><b>Pre-{@code NDR2}</b> (the magic is anything else): the frame MUST be refused at the first
 *       four bytes. That is the flag day; a silent misparse is exactly what the magic exists to
 *       prevent.</li>
 *   <li><b>{@code NDR2}</b>: the frame MUST decode — TLV absorbs additive change, and a genuinely
 *       incompatible change allocates a new kind rather than a new epoch. A kind this build does not
 *       know is allowed (a previous release cannot have emitted one, but a <i>newer</i> corpus
 *       can), and is reported rather than failed, because {@code decodeFrame} answering "unknown
 *       kind" is itself the correct behaviour.</li>
 * </ul>
 *
 * <p>The corpus directory is <b>required to be non-empty</b> once the property is set. A run that
 * inspected zero files would report success while asserting nothing, which is the failure mode this
 * whole test exists to close.
 *
 * <p>Thread-context: JUnit test; single-threaded.
 */
class PreviousReleaseCorpusTest {

    /** Directory of {@code .bin} frames emitted by a previous revision of this project. */
    static final String CORPUS_PROPERTY = "nodera.wire.previousCorpus";

    /** {@code NDR2}, the current frame magic, as it appears in the first four bytes. */
    private static final byte[] NDR2 = {'N', 'D', 'R', '2'};

    private static List<Path> frames(Path dir) throws IOException {
        try (var files = Files.walk(dir)) {
            return files.filter(f -> f.toString().endsWith(".bin")).sorted().toList();
        }
    }

    private static boolean isNdr2(byte[] frame) {
        if (frame.length < NDR2.length) {
            return false;
        }
        for (int i = 0; i < NDR2.length; i++) {
            if (frame[i] != NDR2[i]) {
                return false;
            }
        }
        return true;
    }

    @Test
    void thePreviousReleasesFramesAreDecodedOrRefusedAtTheMagic() throws IOException {
        String configured = System.getProperty(CORPUS_PROPERTY, "").trim();
        if (configured.isEmpty()) {
            // Not a skip that can be mistaken for a pass: the only caller that has a previous
            // corpus is CI, and CI reads this test's own result out of the JUnit XML, so a run that
            // never reached the assertions below is a failed job there.
            System.out.println("[previous-release] -D" + CORPUS_PROPERTY + " not set; nothing to "
                    + "compare against in this run. CI supplies it and fails if this test does not "
                    + "execute.");
            return;
        }

        Path dir = Paths.get(configured).toAbsolutePath();
        assertTrue(Files.isDirectory(dir),
                CORPUS_PROPERTY + " points at " + dir + ", which is not a directory");
        List<Path> frames = frames(dir);
        assertFalseEmpty(frames, dir);

        List<String> unknownKinds = new ArrayList<>();
        int decoded = 0;
        int refused = 0;
        for (Path file : frames) {
            byte[] frame = Files.readAllBytes(file);
            String name = dir.relativize(file).toString();

            if (!isNdr2(frame)) {
                assertThrows(IllegalStateException.class, () -> WireCodec.decodeFrame(frame),
                        name + ": a pre-NDR2 frame must be refused at the magic, not interpreted");
                refused++;
                continue;
            }

            WireCodec.DecodedFrame result;
            try {
                result = WireCodec.decodeFrame(frame);
            } catch (RuntimeException failure) {
                fail(name + ": the current build could not read a frame a previous release emitted."
                        + " NDR2 is additive, so this is an incompatible wire change: " + failure);
                throw failure; // unreachable; keeps the compiler happy about `result`.
            }
            assertNotNull(result);
            if (result.message().isEmpty()) {
                // A kind from the future. The connection survives, which is the contract.
                unknownKinds.add(name + " (kind " + result.kind() + ")");
                continue;
            }

            // Decoding is not enough: the value has to survive this build's own round trip, or the
            // "compatible" claim would cover reading but not answering.
            NoderaMessage message = result.message().orElseThrow();
            byte[] reEncoded = WireCodec.encode(message);
            NoderaMessage again = WireCodec.decode(reEncoded);
            assertEquals(message, again, name + ": re-encoding what a previous release sent is not "
                    + "stable under this build's own codec");
            assertArrayEquals(reEncoded, WireCodec.encode(again),
                    name + ": re-encode is not canonical");
            decoded++;
        }

        System.out.println("[previous-release] " + frames.size() + " frames from " + dir + ": "
                + decoded + " decoded, " + refused + " refused at the magic, "
                + unknownKinds.size() + " of an unknown kind " + unknownKinds);
        assertTrue(decoded + refused + unknownKinds.size() == frames.size(),
                "every frame in the previous corpus must reach a verdict");
        assertTrue(decoded + refused > 0,
                "the previous corpus produced no verdict other than 'unknown kind', which asserts "
                        + "nothing about compatibility");
    }

    private static void assertFalseEmpty(List<Path> frames, Path dir) {
        assertTrue(!frames.isEmpty(), "the previous-release corpus at " + dir + " holds no .bin "
                + "frames. Passing on that basis would report compatibility that was never checked.");
    }
}
