// @generated by java/transport's WireSchemaGenerator from
// java/transport/src/main/java/dev/nodera/protocol/wire/WireRegistry.java.
//
// DO NOT EDIT BY HAND. Add the kind to WireRegistry and re-run:
//     ./gradlew :transport:test --tests '*WireSchemaGeneratorTest' \
//         -Dnodera.wire.regenerate=true

//! The wire schema, mirrored from Java.
//!
//! Both implementations read the same numbers because both are produced from the same
//! table. `tests/tag_mirror.rs` re-parses the Java source and fails if this file has
//! drifted from it, so a kind cannot exist on one side alone.

/// The wire epoch this build speaks; it appears in every frame header.
pub const WIRE_EPOCH: u16 = 2;

/// Message frame kinds. Assigning a number is permanent: never renumber, never reuse.
pub mod message_tags {
    /// `ClientHello` — infrastructure plane.
    pub const CLIENT_HELLO: u16 = 1;
    /// `ServerHello` — infrastructure plane.
    pub const SERVER_HELLO: u16 = 2;
    /// `ChallengeResponse` — infrastructure plane.
    pub const CHALLENGE_RESPONSE: u16 = 3;
    /// `WorkerActivation` — infrastructure plane.
    pub const WORKER_ACTIVATION: u16 = 4;
    /// `RegionAssigned` — consensus plane.
    pub const REGION_ASSIGNED: u16 = 5;
    /// `RegionRevoked` — consensus plane.
    pub const REGION_REVOKED: u16 = 6;
    /// `LeaseRenewal` — consensus plane.
    pub const LEASE_RENEWAL: u16 = 7;
    /// `SnapshotAnnounce` — consensus plane.
    pub const SNAPSHOT_ANNOUNCE: u16 = 8;
    /// `StreamChunk` — consensus plane.
    pub const STREAM_CHUNK: u16 = 9;
    /// `ActionBatchMsg` — consensus plane.
    pub const ACTION_BATCH_MSG: u16 = 10;
    /// `RegionProposal` — consensus plane.
    pub const REGION_PROPOSAL: u16 = 11;
    /// `ValidationVote` — consensus plane.
    pub const VALIDATION_VOTE: u16 = 12;
    /// `CommitAnnounce` — consensus plane.
    pub const COMMIT_ANNOUNCE: u16 = 13;
    /// `ResyncRequest` — consensus plane.
    pub const RESYNC_REQUEST: u16 = 14;
    /// `Heartbeat` — infrastructure plane.
    pub const HEARTBEAT: u16 = 15;
    /// `WorkerLoad` — infrastructure plane.
    pub const WORKER_LOAD: u16 = 16;
    /// `EchoTest` — infrastructure plane.
    pub const ECHO_TEST: u16 = 17;
    /// `RelayEnvelope` — infrastructure plane.
    pub const RELAY_ENVELOPE: u16 = 18;
    /// `PeerJoin` — infrastructure plane.
    pub const PEER_JOIN: u16 = 19;
    /// `MembershipUpdate` — infrastructure plane.
    pub const MEMBERSHIP_UPDATE: u16 = 20;
    /// `PeerGoodbye` — infrastructure plane.
    pub const PEER_GOODBYE: u16 = 21;
    /// `GatewayClaim` — infrastructure plane.
    pub const GATEWAY_CLAIM: u16 = 22;
    /// `SessionKeepAlive` — infrastructure plane.
    pub const SESSION_KEEP_ALIVE: u16 = 23;
    /// `ContentRequest` — infrastructure plane.
    pub const CONTENT_REQUEST: u16 = 24;
    /// `ContentChunk` — infrastructure plane.
    pub const CONTENT_CHUNK: u16 = 25;
    /// `ContentAvailability` — infrastructure plane.
    pub const CONTENT_AVAILABILITY: u16 = 26;
    /// `TrackerQuery` — infrastructure plane.
    pub const TRACKER_QUERY: u16 = 27;
    /// `TrackerResponse` — infrastructure plane.
    pub const TRACKER_RESPONSE: u16 = 28;
    /// `InventoryAdvertisement` — infrastructure plane.
    pub const INVENTORY_ADVERTISEMENT: u16 = 29;
    /// `ArchiveReplicaAssignment` — infrastructure plane.
    pub const ARCHIVE_REPLICA_ASSIGNMENT: u16 = 30;
    /// `ArchiveReplicaAck` — infrastructure plane.
    pub const ARCHIVE_REPLICA_ACK: u16 = 31;
    /// `ExternalDelta` — consensus plane.
    pub const EXTERNAL_DELTA: u16 = 32;
    /// `TrackerAnnounce` — infrastructure plane.
    pub const TRACKER_ANNOUNCE: u16 = 33;
    /// `TrackerAnnounceAck` — infrastructure plane.
    pub const TRACKER_ANNOUNCE_ACK: u16 = 34;
    /// `RendezvousRegister` — infrastructure plane.
    pub const RENDEZVOUS_REGISTER: u16 = 35;
    /// `RendezvousDiscover` — infrastructure plane.
    pub const RENDEZVOUS_DISCOVER: u16 = 36;
    /// `RendezvousPeers` — infrastructure plane.
    pub const RENDEZVOUS_PEERS: u16 = 37;
    /// `RelayReserve` — infrastructure plane.
    pub const RELAY_RESERVE: u16 = 38;
    /// `RelayReservation` — infrastructure plane.
    pub const RELAY_RESERVATION: u16 = 39;
    /// `RelayConnect` — infrastructure plane.
    pub const RELAY_CONNECT: u16 = 40;
    /// `RelayIncoming` — infrastructure plane.
    pub const RELAY_INCOMING: u16 = 41;
    /// `PunchSync` — infrastructure plane.
    pub const PUNCH_SYNC: u16 = 42;
    /// `ObservedAddress` — infrastructure plane.
    pub const OBSERVED_ADDRESS: u16 = 43;
    /// `TrackerCatalogQuery` — infrastructure plane.
    pub const TRACKER_CATALOG_QUERY: u16 = 44;
    /// `TrackerCatalogResponse` — infrastructure plane.
    pub const TRACKER_CATALOG_RESPONSE: u16 = 45;
    /// `EntityTransferPrepare` — consensus plane.
    pub const ENTITY_TRANSFER_PREPARE: u16 = 46;
    /// `EntityTransferAccept` — consensus plane.
    pub const ENTITY_TRANSFER_ACCEPT: u16 = 47;
    /// `EntityTransferCommit` — consensus plane.
    pub const ENTITY_TRANSFER_COMMIT: u16 = 48;
    /// `TrackerRoutesQuery` — infrastructure plane.
    pub const TRACKER_ROUTES_QUERY: u16 = 49;
    /// `TrackerRoutesResponse` — infrastructure plane.
    pub const TRACKER_ROUTES_RESPONSE: u16 = 50;
    /// `WorldManifestQuery` — infrastructure plane.
    pub const WORLD_MANIFEST_QUERY: u16 = 51;
    /// `WorldManifestAnswer` — infrastructure plane.
    pub const WORLD_MANIFEST_ANSWER: u16 = 52;
    /// `ActionForward` — consensus plane.
    pub const ACTION_FORWARD: u16 = 53;
    /// `EventSyncQuery` — consensus plane.
    pub const EVENT_SYNC_QUERY: u16 = 54;
    /// `EventSyncAnswer` — consensus plane.
    pub const EVENT_SYNC_ANSWER: u16 = 55;
    /// `HaloUpdate` — consensus plane.
    pub const HALO_UPDATE: u16 = 56;
    /// `GroupMigration` — consensus plane.
    pub const GROUP_MIGRATION: u16 = 57;
    /// `GenesisApprovalRequest` — consensus plane.
    pub const GENESIS_APPROVAL_REQUEST: u16 = 58;
    /// `GenesisApprovalGrant` — consensus plane.
    pub const GENESIS_APPROVAL_GRANT: u16 = 59;
    /// `WorldGrantGossip` — consensus plane.
    pub const WORLD_GRANT_GOSSIP: u16 = 60;
    /// `RegionRefusal` — consensus plane.
    pub const REGION_REFUSAL: u16 = 61;
    /// `WorldOwnershipGossip` — consensus plane.
    pub const WORLD_OWNERSHIP_GOSSIP: u16 = 62;
    /// `TunnelOpen` — infrastructure plane.
    pub const TUNNEL_OPEN: u16 = 63;
    /// `TunnelData` — infrastructure plane.
    pub const TUNNEL_DATA: u16 = 64;
    /// `TunnelClose` — infrastructure plane.
    pub const TUNNEL_CLOSE: u16 = 65;
    /// `WorldDeletionGossip` — consensus plane.
    pub const WORLD_DELETION_GOSSIP: u16 = 66;
    /// `ServiceAnnounce` — infrastructure plane.
    pub const SERVICE_ANNOUNCE: u16 = 67;
    /// `ServiceAnnounceAck` — infrastructure plane.
    pub const SERVICE_ANNOUNCE_ACK: u16 = 68;
    /// `ServiceDirectoryQuery` — infrastructure plane.
    pub const SERVICE_DIRECTORY_QUERY: u16 = 69;
    /// `ServiceDirectoryResponse` — infrastructure plane.
    pub const SERVICE_DIRECTORY_RESPONSE: u16 = 70;
    /// `ServiceScoreReport` — infrastructure plane.
    pub const SERVICE_SCORE_REPORT: u16 = 71;
    /// `ServiceDrainNotice` — infrastructure plane.
    pub const SERVICE_DRAIN_NOTICE: u16 = 72;
    /// `Nack` — infrastructure plane.
    pub const NACK: u16 = 73;
    /// `Hello` — infrastructure plane.
    pub const HELLO: u16 = 74;
    /// `HelloAck` — infrastructure plane.
    pub const HELLO_ACK: u16 = 75;

    /// Highest kind assigned on the Java side; new kinds start at `NEXT_TAG + 1`.
    pub const NEXT_TAG: u16 = 75;
}

/// Which encoding contract governs a kind's body.
///
/// `Consensus` bodies are hashed and signed, so they are strict and byte-exact;
/// `Infrastructure` bodies are TLV, so a field a peer does not know is skipped
/// instead of destroying the rest of the message.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Plane {
    /// Hashed / signed. Strict positional encoding, carried as opaque bytes.
    Consensus,
    /// Reachability and discovery. Forward-compatible TLV.
    Infrastructure,
}

/// One row of the wire schema.
#[derive(Debug, Clone, Copy)]
pub struct KindRow {
    /// The permanent wire number.
    pub kind: u16,
    /// The stable display name — the Java record's simple name.
    pub name: &'static str,
    /// Which encoding contract governs the body.
    pub plane: Plane,
}

/// Every kind, ascending.
pub const KINDS: &[KindRow] = &[
    KindRow {
        kind: 1,
        name: "ClientHello",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 2,
        name: "ServerHello",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 3,
        name: "ChallengeResponse",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 4,
        name: "WorkerActivation",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 5,
        name: "RegionAssigned",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 6,
        name: "RegionRevoked",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 7,
        name: "LeaseRenewal",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 8,
        name: "SnapshotAnnounce",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 9,
        name: "StreamChunk",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 10,
        name: "ActionBatchMsg",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 11,
        name: "RegionProposal",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 12,
        name: "ValidationVote",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 13,
        name: "CommitAnnounce",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 14,
        name: "ResyncRequest",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 15,
        name: "Heartbeat",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 16,
        name: "WorkerLoad",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 17,
        name: "EchoTest",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 18,
        name: "RelayEnvelope",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 19,
        name: "PeerJoin",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 20,
        name: "MembershipUpdate",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 21,
        name: "PeerGoodbye",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 22,
        name: "GatewayClaim",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 23,
        name: "SessionKeepAlive",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 24,
        name: "ContentRequest",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 25,
        name: "ContentChunk",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 26,
        name: "ContentAvailability",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 27,
        name: "TrackerQuery",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 28,
        name: "TrackerResponse",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 29,
        name: "InventoryAdvertisement",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 30,
        name: "ArchiveReplicaAssignment",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 31,
        name: "ArchiveReplicaAck",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 32,
        name: "ExternalDelta",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 33,
        name: "TrackerAnnounce",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 34,
        name: "TrackerAnnounceAck",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 35,
        name: "RendezvousRegister",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 36,
        name: "RendezvousDiscover",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 37,
        name: "RendezvousPeers",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 38,
        name: "RelayReserve",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 39,
        name: "RelayReservation",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 40,
        name: "RelayConnect",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 41,
        name: "RelayIncoming",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 42,
        name: "PunchSync",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 43,
        name: "ObservedAddress",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 44,
        name: "TrackerCatalogQuery",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 45,
        name: "TrackerCatalogResponse",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 46,
        name: "EntityTransferPrepare",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 47,
        name: "EntityTransferAccept",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 48,
        name: "EntityTransferCommit",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 49,
        name: "TrackerRoutesQuery",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 50,
        name: "TrackerRoutesResponse",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 51,
        name: "WorldManifestQuery",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 52,
        name: "WorldManifestAnswer",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 53,
        name: "ActionForward",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 54,
        name: "EventSyncQuery",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 55,
        name: "EventSyncAnswer",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 56,
        name: "HaloUpdate",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 57,
        name: "GroupMigration",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 58,
        name: "GenesisApprovalRequest",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 59,
        name: "GenesisApprovalGrant",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 60,
        name: "WorldGrantGossip",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 61,
        name: "RegionRefusal",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 62,
        name: "WorldOwnershipGossip",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 63,
        name: "TunnelOpen",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 64,
        name: "TunnelData",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 65,
        name: "TunnelClose",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 66,
        name: "WorldDeletionGossip",
        plane: Plane::Consensus,
    },
    KindRow {
        kind: 67,
        name: "ServiceAnnounce",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 68,
        name: "ServiceAnnounceAck",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 69,
        name: "ServiceDirectoryQuery",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 70,
        name: "ServiceDirectoryResponse",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 71,
        name: "ServiceScoreReport",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 72,
        name: "ServiceDrainNotice",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 73,
        name: "Nack",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 74,
        name: "Hello",
        plane: Plane::Infrastructure,
    },
    KindRow {
        kind: 75,
        name: "HelloAck",
        plane: Plane::Infrastructure,
    },
];

/// The row for a kind, or `None` when this build does not know it.
///
/// An unknown kind is a routine event, not an error: a newer peer may send one, and
/// the frame is skipped and answered rather than killing the connection.
pub fn find(kind: u16) -> Option<&'static KindRow> {
    KINDS.iter().find(|row| row.kind == kind)
}

/// The stable display name of a kind.
pub fn name_of(kind: u16) -> Option<&'static str> {
    find(kind).map(|row| row.name)
}

/// Which plane governs a kind's body.
pub fn plane_of(kind: u16) -> Option<Plane> {
    find(kind).map(|row| row.plane)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kinds_are_unique_and_contiguous() {
        for (index, row) in KINDS.iter().enumerate() {
            assert_eq!(
                row.kind as usize,
                index + 1,
                "the kind table must be ascending and contiguous"
            );
        }
        assert_eq!(KINDS.len(), message_tags::NEXT_TAG as usize);
    }

    #[test]
    fn every_kind_resolves_to_itself() {
        for row in KINDS {
            assert_eq!(find(row.kind).map(|r| r.name), Some(row.name));
            assert_eq!(plane_of(row.kind), Some(row.plane));
        }
        assert!(find(message_tags::NEXT_TAG + 1).is_none());
    }
}
