#!/usr/bin/env bash
# ===========================================================================
# nodera telemetry-stack — bring the Big Data plane up, down, or prove it works.
#
#   scripts/telemetry-stack.sh up          ingest + Vector + Redpanda + ClickHouse + Grafana
#   scripts/telemetry-stack.sh up --all    …plus the ops console, Spark, and TLS termination
#   scripts/telemetry-stack.sh down        stop it (add --wipe to delete the collected data)
#   scripts/telemetry-stack.sh smoke       submit one batch and prove the row is queryable
#   scripts/telemetry-stack.sh status      what is running, and what the warehouse holds
#
# NOTHING HERE IS REQUIRED TO PLAY NODERA. This is the project's own analytics
# deployment; a peer that cannot reach it keeps its reports in a bounded spool
# and eventually drops them. the `telemetry` scenario (`scripts/nodera-test.sh run telemetry`) proves exactly that.
# ===========================================================================
set -uo pipefail

NODERA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STACK_DIR="$NODERA_ROOT/docker/telemetry"
TAG="stack"

log()  { printf '\033[1;36m[%s]\033[0m %s\n' "$TAG" "$*"; }
pass() { printf '\033[1;32m[%s] PASS %s\033[0m\n' "$TAG" "$*"; }
die()  { printf '\033[1;31m[%s] %s\033[0m\n' "$TAG" "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is not installed"
docker compose version >/dev/null 2>&1 || die "this docker has no 'compose' subcommand"

compose() { ( cd "$STACK_DIR" && docker compose "$@" ); }

ensure_env() {
    [[ -f "$STACK_DIR/.env" ]] && return 0
    log "no .env — generating one with fresh secrets"
    # The pseudonymisation key is NOT generated here, or anywhere: the ingest mints a fresh
    # per-period key from the OS CSPRNG in memory (docs/telemetry/LIMITATIONS.fixed.md L-72). The
    # secrets this file still holds are the warehouse and dashboard passwords.
    local clickhouse grafana
    clickhouse="$(openssl rand -hex 12 2>/dev/null || date +%s%N | sha256sum | cut -c1-24)"
    grafana="$(openssl rand -hex 12 2>/dev/null || date +%s%N | sha256sum | cut -c25-48)"
    cat > "$STACK_DIR/.env" <<EOF
# Generated by scripts/telemetry-stack.sh. Keep out of git (it already is).
CLICKHOUSE_USER=nodera
CLICKHOUSE_PASSWORD=$clickhouse
GRAFANA_PASSWORD=$grafana
NODERA_TELEMETRY_TLS_PORT=25621
EOF
    log "Grafana password: $grafana (also in $STACK_DIR/.env)"
}

case "${1:-}" in
    up)
        ensure_env
        shift || true
        profiles=()
        [[ "${1:-}" == "--all" ]] && profiles=(--profile ops --profile analytics --profile public)
        log "starting the telemetry plane"
        compose "${profiles[@]}" up -d --build || die "docker compose up failed"
        log "waiting for ClickHouse"
        for _ in $(seq 1 60); do
            compose exec -T clickhouse wget -q --spider http://localhost:8123/ping 2>/dev/null \
                && break
            sleep 2
        done
        pass "up — Grafana http://localhost:3000 · ClickHouse http://localhost:8123 · ingest 127.0.0.1:25620"
        ;;

    down)
        shift || true
        if [[ "${1:-}" == "--wipe" ]]; then
            log "stopping AND DELETING every volume (the collected data goes with them)"
            compose down -v
        else
            compose down
        fi
        pass "down"
        ;;

    smoke)
        # The telemetry 2 acceptance criterion: a submitted batch becomes a queryable row.
        ensure_env
        log "submitting one batch to the ingest service"
        install="$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
        now="$(( $(date +%s) * 1000 ))"
        body="{\"v\":1,\"src\":\"peer\",\"consent\":\"granted\",\"install\":\"$install\",\
\"agent\":\"stack-smoke\",\"sent_at\":$now,\"events\":[{\"name\":\"feature.use\",\"t\":$now,\
\"attrs\":{\"feature\":\"selftest\",\"count\":1}}]}"
        reply="$(python3 - 25620 "$body" <<'PY'
import socket, struct, sys
port, body = int(sys.argv[1]), sys.argv[2].encode()
with socket.create_connection(("127.0.0.1", port), timeout=5) as s:
    s.sendall(struct.pack(">I", len(body)) + body)
    header = s.recv(4)
    (length,) = struct.unpack(">I", header)
    out = b""
    while len(out) < length:
        out += s.recv(length - len(out))
    print(out.decode())
PY
)" || die "the ingest service did not answer on 127.0.0.1:25620 — is the stack up?"
        [[ "$reply" == *'"accepted":1'* ]] || die "the batch was not accepted: $reply"
        pass "the collector accepted the batch"

        log "waiting for the row to reach ClickHouse (Vector → Redpanda → warehouse)"
        for _ in $(seq 1 60); do
            rows="$(compose exec -T clickhouse clickhouse-client --user "${CLICKHOUSE_USER:-nodera}" \
                --password "$(grep '^CLICKHOUSE_PASSWORD=' "$STACK_DIR/.env" | cut -d= -f2)" \
                --query "SELECT count() FROM nodera.events WHERE event='feature.use'" 2>/dev/null)"
            [[ "${rows:-0}" -gt 0 ]] && break
            sleep 2
        done
        [[ "${rows:-0}" -gt 0 ]] || die "the row never arrived in the warehouse"
        pass "the row is queryable in ClickHouse ($rows matching row(s))"

        # The privacy assertion, made against what the warehouse actually stores.
        columns="$(compose exec -T clickhouse clickhouse-client --user "${CLICKHOUSE_USER:-nodera}" \
            --password "$(grep '^CLICKHOUSE_PASSWORD=' "$STACK_DIR/.env" | cut -d= -f2)" \
            --query "DESCRIBE nodera.events FORMAT TabSeparated" 2>/dev/null | cut -f1 | tr '\n' ' ')"
        if grep -qE '\b(ip|address|route|node_id)\b' <<<"$columns"; then
            die "the warehouse has an address column: $columns"
        fi
        pass "the warehouse schema has no column that could hold an address"
        ;;

    status)
        compose ps
        ;;

    *)
        sed -n '2,15p' "$0"
        exit 2
        ;;
esac
