package dev.nodera.structure;

import dev.nodera.structure.CodeGraph.ClassInfo;
import dev.nodera.structure.CodeGraph.Finding;
import dev.nodera.structure.CodeGraph.MethodId;
import dev.nodera.structure.HeadlessDebugProbe.RuntimeProfile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders the structural report: what the tree contains, what of it runs, and what costs more than
 * it should.
 *
 * <h2>Reading order is deliberate</h2>
 *
 * <p>The first table is the intersection of "the debugger saw this run" and "the bytecode says this
 * is expensive", because that intersection is the only part of the report that is unambiguously
 * worth someone's afternoon. Dead code comes next (it is free to delete and it is where this
 * repository's defects live), and the raw inventories come last, where they belong.
 *
 * <p>Thread-context: pure functions over an immutable analysis.
 */
final class StructureReport {

    /** Rows per table before the report stops listing and starts counting. */
    private static final int MAX_ROWS = 40;

    private StructureReport() {
    }

    /** The numbers the budget ratchet is asserted against. */
    record Counts(int deadClasses, int testOnlyClasses, int neverReferencedMethods,
                  int testOnlyMethods, int unreachableMethods, int hugeMethods,
                  int severeCostFindings) {

        Map<String, Integer> asMap() {
            Map<String, Integer> out = new LinkedHashMap<>();
            out.put("dead_classes", deadClasses);
            out.put("test_only_classes", testOnlyClasses);
            out.put("never_referenced_methods", neverReferencedMethods);
            out.put("test_only_methods", testOnlyMethods);
            out.put("unreachable_methods", unreachableMethods);
            out.put("huge_methods", hugeMethods);
            out.put("severe_cost_findings", severeCostFindings);
            return out;
        }
    }

    static Counts count(DeadCodeAnalysis analysis, List<Finding> findings) {
        int huge = (int) findings.stream().filter(f -> f.kind().equals("huge-method")).count();
        int severe = (int) findings.stream().filter(f -> f.severity() >= 3).count();
        return new Counts(
                analysis.deadClasses().size(),
                analysis.testOnlyClasses().size(),
                analysis.neverReferenced().size(),
                analysis.testOnly().size(),
                analysis.unreachable().size(),
                huge,
                severe);
    }

    static String render(CodeGraph graph, DeadCodeAnalysis analysis, List<Finding> findings,
                         RuntimeProfile profile) {
        List<String> out = new ArrayList<>();
        Counts counts = count(analysis, findings);
        int productionClasses = graph.productionClasses().size();

        out.add("# Structural code report");
        out.add("");
        out.add("Generated by `:worker:structureReport` from the compiled bytecode of every module, "
                + "plus a debugger-instrumented run of the real `nodera-headless` worker.");
        out.add("");
        out.add("| scope | value |");
        out.add("|---|---:|");
        out.add("| modules scanned | " + String.join(", ", graph.productionModules()) + " |");
        out.add("| production classes | " + productionClasses + " |");
        out.add("| methods analysed | " + analysis.analysedMethods() + " |");
        out.add("| methods not analysable (generated, external override, off-classpath supertype) | "
                + analysis.unanalysableMethods() + " |");
        out.add("| runtime probe | " + (profile.isEmpty()
                ? "not run (static analysis only)"
                : profile.classesLoaded().size() + " classes loaded, "
                        + profile.methodEntries().size() + " distinct methods entered, "
                        + profile.events() + " entry events in " + profile.durationMillis() + " ms")
                + " |");
        out.add("");

        renderPriority(out, findings, profile);
        renderDeadCode(out, graph, analysis, profile);
        renderCost(out, findings, profile);
        renderRuntime(out, graph, analysis, profile);

        out.add("## 6. Budget");
        out.add("");
        out.add("These are the numbers `fixtures/structure/budget.json` ratchets. They may go down "
                + "without ceremony; going up fails `:worker:structureReport`, because every entry "
                + "here is code that ships and does nothing.");
        out.add("");
        out.add("| metric | value |");
        out.add("|---|---:|");
        counts.asMap().forEach((key, value) -> out.add("| `" + key + "` | " + value + " |"));
        out.add("");

        return String.join("\n", out) + "\n";
    }

    private static void renderPriority(List<String> out, List<Finding> findings,
                                       RuntimeProfile profile) {
        out.add("## 1. Costly code that actually runs");
        out.add("");
        if (profile.isEmpty()) {
            out.add("_The runtime probe did not run, so this section cannot be produced: without it "
                    + "there is no way to tell an expensive loop on a hot path from an expensive "
                    + "loop nobody ever enters. Run `./gradlew :worker:structureReport`._");
            out.add("");
            return;
        }
        record Row(Finding finding, long entries) {
        }
        List<Row> rows = new ArrayList<>();
        for (Finding finding : findings) {
            long entries = profile.entriesOf(finding.method());
            if (entries > 0) {
                rows.add(new Row(finding, entries));
            }
        }
        rows.sort(Comparator.<Row>comparingLong(r -> r.entries() * r.finding().severity()).reversed());
        if (rows.isEmpty()) {
            out.add("Nothing: no method the debugger saw execute carries a cost finding. That is the "
                    + "good outcome.");
            out.add("");
            return;
        }
        out.add("Ranked by entries x severity. The debugger entered these methods during a normal "
                + "worker session AND their bytecode carries work that scales badly — this is where "
                + "optimisation pays.");
        out.add("");
        out.add("| method | entries | finding | module |");
        out.add("|---|---:|---|---|");
        for (Row row : rows.subList(0, Math.min(rows.size(), MAX_ROWS))) {
            out.add("| `" + row.finding().method().display() + "` | " + row.entries() + " | "
                    + severity(row.finding().severity()) + " " + row.finding().detail()
                    + (row.finding().count() > 1 ? " (x" + row.finding().count() + ")" : "")
                    + " | " + row.finding().module() + " |");
        }
        if (rows.size() > MAX_ROWS) {
            out.add("");
            out.add("_… and " + (rows.size() - MAX_ROWS) + " more; the full set is in "
                    + "`structure.json`._");
        }
        out.add("");
    }

    private static void renderDeadCode(List<String> out, CodeGraph graph, DeadCodeAnalysis analysis,
                                       RuntimeProfile profile) {
        out.add("## 2. Dead code");
        out.add("");
        out.add("Three verdicts at three confidence levels. Nothing whose caller could be outside "
                + "our bytecode (JDK/NeoForge/JUnit dispatch, generated members, off-classpath "
                + "supertypes) appears here at all.");
        out.add("");

        out.add("### 2.1 Classes nothing references (" + analysis.deadClasses().size() + ")");
        out.add("");
        if (analysis.deadClasses().isEmpty()) {
            out.add("None.");
        } else {
            out.add("| class | module |");
            out.add("|---|---|");
            for (ClassInfo info : head(analysis.deadClasses())) {
                out.add("| `" + info.display() + "` | " + info.module() + " |");
            }
            more(out, analysis.deadClasses().size());
        }
        out.add("");

        out.add("### 2.2 Classes only tests and benchmarks reference ("
                + analysis.testOnlyClasses().size() + ")");
        out.add("");
        out.add("Built, covered, and wired to nothing that ships. This is the shape of defect this "
                + "project keeps finding by hand.");
        out.add("");
        if (analysis.testOnlyClasses().isEmpty()) {
            out.add("None.");
        } else {
            out.add("| class | module | loaded at runtime? |");
            out.add("|---|---|:--:|");
            for (ClassInfo info : head(analysis.testOnlyClasses())) {
                String loaded = profile.isEmpty() ? "—" : (profile.loaded(info.name()) ? "yes" : "no");
                out.add("| `" + info.display() + "` | " + info.module() + " | " + loaded + " |");
            }
            more(out, analysis.testOnlyClasses().size());
        }
        out.add("");

        out.add("### 2.3 Methods nothing references (" + analysis.neverReferenced().size() + ")");
        out.add("");
        methodTable(out, analysis.neverReferenced(), graph);

        out.add("### 2.4 Methods only tests and benchmarks call (" + analysis.testOnly().size() + ")");
        out.add("");
        methodTable(out, analysis.testOnly(), graph);

        out.add("### 2.5 Methods no entry point can reach (" + analysis.unreachable().size() + ")");
        out.add("");
        out.add("Referenced by production code, but only by production code that is itself "
                + "unreachable: a dead cluster keeping itself warm.");
        out.add("");
        methodTable(out, analysis.unreachable(), graph);
    }

    private static void renderCost(List<String> out, List<Finding> findings, RuntimeProfile profile) {
        out.add("## 3. Cost findings");
        out.add("");
        out.add("Facts about the emitted bytecode, not style opinions: an allocation inside a loop "
                + "IS an allocation per iteration, and a method past HotSpot's "
                + CodeGraph.HUGE_METHOD_BYTES + "-byte limit IS one the JIT declines to compile. "
                + "Whether each one matters depends on section 1.");
        out.add("");
        Map<String, Integer> byKind = new LinkedHashMap<>();
        findings.forEach(f -> byKind.merge(f.kind(), 1, Integer::sum));
        out.add("| kind | count |");
        out.add("|---|---:|");
        byKind.entrySet().stream()
                .sorted(Map.Entry.<String, Integer>comparingByValue().reversed())
                .forEach(e -> out.add("| `" + e.getKey() + "` | " + e.getValue() + " |"));
        out.add("");

        List<Finding> severe = findings.stream().filter(f -> f.severity() >= 3).toList();
        out.add("### 3.1 Severe (" + severe.size() + ")");
        out.add("");
        if (severe.isEmpty()) {
            out.add("None.");
        } else {
            out.add("| method | finding | entries | module |");
            out.add("|---|---|---:|---|");
            for (Finding finding : head(severe)) {
                long entries = profile.entriesOf(finding.method());
                out.add("| `" + finding.method().display() + "` | " + finding.detail() + " | "
                        + (profile.isEmpty() ? "—" : String.valueOf(entries)) + " | "
                        + finding.module() + " |");
            }
            more(out, severe.size());
        }
        out.add("");
    }

    private static void renderRuntime(List<String> out, CodeGraph graph, DeadCodeAnalysis analysis,
                                      RuntimeProfile profile) {
        out.add("## 4. What the debugger saw");
        out.add("");
        if (profile.isEmpty()) {
            out.add("_Not run._");
            out.add("");
            return;
        }
        out.add("Control verbs driven against the live worker, in order:");
        out.add("");
        profile.scenario().forEach(step -> out.add("- `" + step + "`"));
        out.add("");

        // Lambda proxy classes (`Foo$$Lambda.0x…`) are JVM implementation detail with an address in
        // their name: they would fill the table with rows nobody can act on and a different address
        // every run.
        List<Map.Entry<String, Long>> hottest = profile.methodEntries().entrySet().stream()
                .filter(entry -> !entry.getKey().contains("$$Lambda"))
                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
                .collect(java.util.stream.Collectors.toCollection(ArrayList::new));
        out.add("### 4.1 Hottest methods by entry count");
        out.add("");
        out.add("Counts are exact; times are not measured here at all (method-entry tracing "
                + "deoptimises the process, so any duration it produced would be a measurement of "
                + "the debugger). Speed lives in `BENCHMARKS.md`.");
        out.add("");
        out.add("| method | entries |");
        out.add("|---|---:|");
        for (Map.Entry<String, Long> entry : hottest.subList(0, Math.min(hottest.size(), 25))) {
            out.add("| `" + entry.getKey().replace('/', '.') + "` | " + entry.getValue() + " |");
        }
        out.add("");

        long never = graph.productionClasses().stream()
                .filter(c -> !profile.loaded(c.name()))
                .count();
        out.add("### 4.2 Coverage of a normal worker session");
        out.add("");
        out.add("- production classes loaded: **" + (graph.productionClasses().size() - never) + "** of "
                + graph.productionClasses().size());
        out.add("- never loaded during the session: **" + never + "** (expected — the mod-side, "
                + "Paper-side and hosting-only lanes are not exercised by a read-only scenario)");
        out.add("");

        List<String> contradictions = new ArrayList<>();
        for (MethodId method : analysis.unreachable()) {
            if (profile.entriesOf(method) > 0) {
                contradictions.add(method.display());
            }
        }
        for (MethodId method : analysis.neverReferenced()) {
            if (profile.entriesOf(method) > 0) {
                contradictions.add(method.display() + " (reported unreferenced!)");
            }
        }
        out.add("### 4.3 Static analysis contradicted by the running process");
        out.add("");
        if (contradictions.isEmpty()) {
            out.add("None: nothing the analysis called dead was seen executing.");
        } else {
            out.add("**These executed despite being reported as dead — the static analysis is wrong "
                    + "about them and needs a rule, not the code:**");
            out.add("");
            contradictions.forEach(entry -> out.add("- `" + entry + "`"));
        }
        out.add("");

        out.add("## 5. Inventory");
        out.add("");
        Map<String, Integer> perModule = new LinkedHashMap<>();
        graph.productionClasses().forEach(c -> perModule.merge(c.module(), 1, Integer::sum));
        out.add("| module | production classes |");
        out.add("|---|---:|");
        perModule.forEach((module, count) -> out.add("| `" + module + "` | " + count + " |"));
        out.add("");
    }

    private static void methodTable(List<String> out, List<MethodId> methods, CodeGraph graph) {
        if (methods.isEmpty()) {
            out.add("None.");
            out.add("");
            return;
        }
        out.add("| method | module |");
        out.add("|---|---|");
        for (MethodId method : head(methods)) {
            ClassInfo owner = graph.classInfo(method.owner());
            out.add("| `" + method.display() + "` | " + (owner == null ? "?" : owner.module()) + " |");
        }
        more(out, methods.size());
        out.add("");
    }

    private static <T> List<T> head(List<T> values) {
        return values.subList(0, Math.min(values.size(), MAX_ROWS));
    }

    private static void more(List<String> out, int total) {
        if (total > MAX_ROWS) {
            out.add("");
            out.add("_… and " + (total - MAX_ROWS) + " more; the full list is in `structure.json`._");
        }
    }

    private static String severity(int severity) {
        return switch (severity) {
            case 3 -> "🔴";
            case 2 -> "🟠";
            default -> "🟡";
        };
    }

    /** The machine-readable half: everything the Markdown truncates. */
    static void writeJson(Path file, CodeGraph graph, DeadCodeAnalysis analysis,
                          List<Finding> findings, RuntimeProfile profile) throws IOException {
        Files.createDirectories(file.getParent());
        StringBuilder json = new StringBuilder("{\n");
        Counts counts = count(analysis, findings);
        json.append("  \"counts\": {");
        List<Map.Entry<String, Integer>> entries = new ArrayList<>(counts.asMap().entrySet());
        for (int i = 0; i < entries.size(); i++) {
            json.append(i == 0 ? "\n    " : ",\n    ")
                    .append('"').append(entries.get(i).getKey()).append("\": ")
                    .append(entries.get(i).getValue());
        }
        json.append("\n  },\n");
        json.append("  \"analysedMethods\": ").append(analysis.analysedMethods()).append(",\n");
        json.append("  \"unanalysableMethods\": ").append(analysis.unanalysableMethods()).append(",\n");
        json.append("  \"runtimeProbe\": ").append(profile.isEmpty() ? "false" : "true").append(",\n");
        appendList(json, "deadClasses", analysis.deadClasses().stream().map(ClassInfo::display).toList());
        json.append(",\n");
        appendList(json, "testOnlyClasses",
                analysis.testOnlyClasses().stream().map(ClassInfo::display).toList());
        json.append(",\n");
        appendList(json, "neverReferencedMethods",
                analysis.neverReferenced().stream().map(MethodId::display).toList());
        json.append(",\n");
        appendList(json, "testOnlyMethods",
                analysis.testOnly().stream().map(MethodId::display).toList());
        json.append(",\n");
        appendList(json, "unreachableMethods",
                analysis.unreachable().stream().map(MethodId::display).toList());
        json.append(",\n");
        appendList(json, "costFindings", findings.stream()
                .map(f -> f.method().display() + " :: " + f.kind() + " :: " + f.detail())
                .toList());
        json.append("\n}\n");
        Files.writeString(file, json.toString());
    }

    private static void appendList(StringBuilder json, String name, List<String> values) {
        json.append("  \"").append(name).append("\": [");
        for (int i = 0; i < values.size(); i++) {
            json.append(i == 0 ? "\n    " : ",\n    ").append('"')
                    .append(values.get(i).replace("\\", "\\\\").replace("\"", "\\\"")).append('"');
        }
        json.append(values.isEmpty() ? "]" : "\n  ]");
    }
}
