// About — what this build is, and what it is built out of.
//
// The package list is generated by scripts/collect-licenses.py from the same manifests the build
// reads, and embedded at compile time, so it describes this binary rather than whatever was last
// committed. A licence that could not be read locally is shown as unknown; it is never inferred.
import { useEffect, useMemo, useState } from "react";
import { FiExternalLink, FiSearch } from "react-icons/fi";
import { Card, Empty, KeyValue, MONO, Pill, Td, Th, Tr, cx } from "./components";
import { UNKNOWN, formatDate } from "./api";
import { aboutBuild, type AboutBuild, type Package } from "./play";
import { linkNote, useExternalLink } from "./links";

const ECOSYSTEMS = [
  { id: "rust", label: "Rust" },
  { id: "npm", label: "Frontend" },
  { id: "java", label: "Java" },
] as const;

export function AboutScreen() {
  const [build, setBuild] = useState<AboutBuild | null>(null);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  // Opening the repository link, with the clipboard as the fallback when nothing on this
  // machine can open a browser.
  const repository = useExternalLink();

  useEffect(() => {
    aboutBuild()
      .then(setBuild)
      .catch((e: unknown) => setError(String(e)));
  }, []);

  const matches = useMemo(() => {
    if (!build) return [];
    const needle = query.trim().toLowerCase();
    if (!needle) return build.packages;
    return build.packages.filter(
      (p) =>
        p.name.toLowerCase().includes(needle) || p.licence.toLowerCase().includes(needle),
    );
  }, [build, query]);

  const byEcosystem = (id: string) => matches.filter((p) => p.ecosystem === id);

  if (error) {
    return (
      <div className="px-[26px] pt-5">
        <Card title="About">
          <p className="py-2 text-sm text-danger">{error}</p>
        </Card>
      </div>
    );
  }

  if (!build) {
    return (
      <div className="px-[26px] pt-5">
        <Card title="About">
          <p className="py-2 text-sm text-faint">Reading this build…</p>
        </Card>
      </div>
    );
  }

  const unknown = build.packages.filter((p) => !p.licence).length;

  return (
    <div className="flex max-w-[1100px] flex-col gap-4 px-[26px] pt-5 pb-10">
      <Card title={build.name}>
        <dl>
          <KeyValue label="Version" value={build.version} mono />
          <KeyValue label="Licence" value={build.licence} />
          <KeyValue label="Control protocol" value={`v${build.protocol_version}`} />
          {/* A real link again. It was a copy-to-clipboard button because `<a target="_blank">`
              opens nothing in a Tauri v2 webview and this app depended on no opener — a workaround
              that told the truth about the link not working. The host opens it now, and the
              clipboard is what happens when the host cannot. */}
          <KeyValue
            label="Repository"
            value={
              <button
                type="button"
                title={build.repository}
                disabled={repository.state.status === "opening"}
                className="inline-flex items-center gap-1.5 text-brand-3 hover:underline"
                onClick={() => repository.open(build.repository)}
              >
                {build.repository}
                <FiExternalLink aria-hidden className="inline" />
                {linkNote(repository.state) && (
                  <span className="text-xs text-dim">{linkNote(repository.state)}</span>
                )}
              </button>
            }
          />
          <KeyValue label="Settings folder" value={build.config_dir} mono />
          <KeyValue label="Saved invitations" value={build.share_dir} mono />
        </dl>
      </Card>

      <Card
        title="Third-party packages"
        right={
          <div className="flex items-center gap-2">
            {unknown > 0 && <Pill tone="muted">{unknown} unknown</Pill>}
            <span className="text-faint">
              <FiSearch aria-hidden />
            </span>
            <input
              className="w-[190px] rounded-sm border border-line bg-surface-2 px-2.5 py-[6px] text-sm focus:border-brand-2 focus:outline-none"
              placeholder="Search name or licence"
              value={query}
              onChange={(e) => setQuery(e.currentTarget.value)}
            />
          </div>
        }
      >
        <p className="pb-2 text-xs text-faint">
          Direct dependencies · generated {formatDate(Date.parse(build.licences_generated_at))}
        </p>
        {matches.length === 0 ? (
          <Empty title="Nothing matches that" />
        ) : (
          ECOSYSTEMS.map(({ id, label }) => {
            const rows = byEcosystem(id);
            if (rows.length === 0) return null;
            return (
              <section key={id} className="pt-1 pb-2">
                <h3 className="pb-1 text-2xs tracking-[0.08em] text-faint uppercase">
                  {label} · {rows.length}
                </h3>
                <div className="overflow-x-auto">
                  <table className="w-full border-collapse text-sm">
                    <thead>
                      <Tr>
                        <Th>Package</Th>
                        <Th>Version</Th>
                        <Th>Licence</Th>
                      </Tr>
                    </thead>
                    <tbody>
                      {rows.map((p) => (
                        <PackageRow key={`${p.ecosystem}:${p.name}`} package={p} />
                      ))}
                    </tbody>
                  </table>
                </div>
              </section>
            );
          })
        )}
      </Card>
    </div>
  );
}

function PackageRow(props: { package: Package }) {
  const p = props.package;
  return (
    <Tr>
      <Td mono>{p.name}</Td>
      <Td mono>{p.version || UNKNOWN}</Td>
      {/* An empty licence is a licence the generator could not read from the package's own
          metadata. Rendering a guess here would be an attribution nobody checked. */}
      <Td>
        <span className={cx(!p.licence && "text-faint", p.licence && MONO)}>
          {p.licence || UNKNOWN}
        </span>
      </Td>
    </Tr>
  );
}
