// About — what this build is, and what it is built out of.
//
// The package list is generated by scripts/collect-licenses.py from the same manifests the build
// reads, and embedded at compile time, so it describes this binary rather than whatever was last
// committed. A licence that could not be read locally is shown as unknown; it is never inferred.
import { useEffect, useMemo, useState } from "react";
import { FiExternalLink } from "react-icons/fi";
import { Card, DataTable, Empty, FilterBar, KeyValue, MONO, Pagination, Pill, Td, Th, Tr, cx } from "./components";
import { UNKNOWN, formatDate } from "./api";
import { aboutBuild, type AboutBuild, type Package } from "./play";
import { linkNote, useExternalLink } from "./links";

const ECOSYSTEMS = [
  { id: "rust", label: "Rust" },
  { id: "npm", label: "Frontend" },
  { id: "java", label: "Java" },
] as const;

export function AboutScreen() {
  const [build, setBuild] = useState<AboutBuild | null>(null);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  const [page, setPage] = useState(1);
  // Opening the repository link. The host's ladder ends in a window of our own, so this always
  // shows the page — there is no clipboard consolation prize.
  const repository = useExternalLink();

  useEffect(() => {
    aboutBuild()
      .then(setBuild)
      .catch((e: unknown) => setError(String(e)));
  }, []);

  const matches = useMemo(() => {
    if (!build) return [];
    const needle = query.trim().toLowerCase();
    if (!needle) return build.packages;
    return build.packages.filter(
      (p) =>
        p.name.toLowerCase().includes(needle) || p.licence.toLowerCase().includes(needle),
    );
  }, [build, query]);
  const pageSize = 15;
  const visible = matches.slice((page - 1) * pageSize, page * pageSize);
  const byEcosystem = (id: string) => visible.filter((p) => p.ecosystem === id);
  useEffect(() => {
    const last = Math.max(1, Math.ceil(matches.length / pageSize));
    if (page > last) setPage(last);
  }, [matches.length, page]);

  if (error) {
    return (
      <div>
        <Card title="About">
          <p className="py-2 text-sm text-danger">{error}</p>
        </Card>
      </div>
    );
  }

  if (!build) {
    return (
      <div>
        <Card title="About">
          <p className="py-2 text-sm text-faint">Reading this build…</p>
        </Card>
      </div>
    );
  }

  const unknown = build.packages.filter((p) => !p.licence).length;

  return (
    <div className="flex flex-col gap-4">
      <Card title={build.name}>
        <dl>
          <KeyValue label="Version" value={build.version} mono />
          <KeyValue label="Licence" value={build.licence} />
          <KeyValue label="Control protocol" value={`v${build.protocol_version}`} />
          {/* A real link again. It was a copy-to-clipboard button because `<a target="_blank">`
              opens nothing in a Tauri v2 webview and this app depended on no opener — a workaround
              that told the truth about the link not working. The host opens it now: the default
              browser, or failing that a window pointed at the page. */}
          <KeyValue
            label="Repository"
            value={
              <button
                type="button"
                title={build.repository}
                disabled={repository.state.status === "opening"}
                className="inline-flex items-center gap-1.5 text-brand-3 hover:underline"
                onClick={() => repository.open(build.repository)}
              >
                {build.repository}
                <FiExternalLink aria-hidden className="inline" />
                {linkNote(repository.state) && (
                  <span className="text-xs text-dim">{linkNote(repository.state)}</span>
                )}
              </button>
            }
          />
          <KeyValue label="Settings folder" value={build.config_dir} mono />
          <KeyValue label="Saved invitations" value={build.share_dir} mono />
        </dl>
      </Card>

      <Card
        title="Third-party packages"
        right={unknown > 0 && <Pill tone="muted">{unknown} unknown</Pill>}
      >
        <FilterBar
          label="Search third-party packages"
          value={query}
          onChange={(value) => {
            setQuery(value);
            setPage(1);
          }}
          placeholder="Search package or licence"
        />
        <p className="pb-2 text-xs text-faint">
          Direct dependencies · generated {formatDate(Date.parse(build.licences_generated_at))}
        </p>
        {matches.length === 0 ? (
          <Empty title="Nothing matches that" />
        ) : (
          // Three tables of three narrow columns. Stacked, each one stretched a package name and a
          // licence to opposite ends of the canvas and pushed the next ecosystem below the fold;
          // side by side they are the width their content actually is, and a wide window shows all
          // three at once instead of one and a scrollbar.
          <div className="grid gap-4 pt-1 pb-2 grid-cols-[repeat(auto-fit,minmax(min(100%,340px),1fr))] [&>*]:min-w-0">
            {ECOSYSTEMS.map(({ id, label }) => {
              const rows = byEcosystem(id);
              if (rows.length === 0) return null;
              return (
                <section key={id}>
                  <h3 className="pb-1 text-2xs tracking-[0.08em] text-faint uppercase">
                    {label} · {rows.length}
                  </h3>
                  <DataTable label={`${label} packages`}>
                    <thead>
                      <Tr>
                        <Th>Package</Th>
                        <Th>Version</Th>
                        <Th>Licence</Th>
                      </Tr>
                    </thead>
                    <tbody>
                      {rows.map((p) => (
                        <PackageRow key={`${p.ecosystem}:${p.name}`} package={p} />
                      ))}
                    </tbody>
                  </DataTable>
                </section>
              );
            })}
          </div>
        )}
        <Pagination page={page} pageSize={pageSize} total={matches.length} onPage={setPage} />
      </Card>
    </div>
  );
}

function PackageRow(props: { package: Package }) {
  const p = props.package;
  return (
    <Tr>
      <Td mono>{p.name}</Td>
      <Td mono>{p.version || UNKNOWN}</Td>
      {/* An empty licence is a licence the generator could not read from the package's own
          metadata. Rendering a guess here would be an attribution nobody checked. */}
      <Td>
        <span className={cx(!p.licence && "text-faint", p.licence && MONO)}>
          {p.licence || UNKNOWN}
        </span>
      </Td>
    </Tr>
  );
}
